// Pixel sprites, one string per row. '.' is transparent; every other char maps to PALETTE.
// Colors are from the Sweetie 16 palette plus a skin tone and a hair brown.
export const PALETTE: Record<string, string> = {
  k: '#0f0f1b',
  w: '#f4f4f4',
  s: '#94b0c2',
  S: '#566c86',
  y: '#ffcd75',
  o: '#ef7d57',
  r: '#b13e53',
  g: '#a7f070',
  G: '#38b764',
  T: '#257179',
  b: '#41a6f6',
  B: '#3b5dc9',
  n: '#29366f',
  c: '#73eff7',
  p: '#5d275d',
  t: '#f7c59f',
  h: '#7a4a2a',
  O: '#c05818',
  m: '#f89898',
  v: '#b088e0',
  V: '#7050a8',
  a: '#c0c0d0',
  A: '#787890',
  l: '#c8f0f8',
}

export type SpriteName = keyof typeof SPRITES

export const SPRITES = {
  house: [
    '.....kk.....',
    '....kook....',
    '...kooook...',
    '..kooooook..',
    '.kooooooook.',
    'kkkkkkkkkkkk',
    '.kyyyyyyyyk.',
    '.kybbyykkyk.',
    '.kybbyykoyk.',
    '.kyyyyykoyk.',
    '.kyyyyykoyk.',
    '.kkkkkkkkkk.',
  ],
  sword: [
    '..........kk',
    '.........kwk',
    '........kwsk',
    '.......kwsk.',
    '......kwsk..',
    '.....kwsk...',
    '.kk.kwsk....',
    '.kykwsk.....',
    '..kyyk......',
    '.kokyyk.....',
    'kokk.kyk....',
    'kk....kk....',
  ],
  meat: [
    '......kkkk..',
    '.....koooyk.',
    '....kooooyyk',
    '....koooooyk',
    '....kroooook',
    '.....krrrrk.',
    '....kwkkkk..',
    '...kwk......',
    '.kkwk.......',
    'kwwwk.......',
    'kwwk........',
    '.kk.........',
  ],
  potion: [
    '....kkkk....',
    '....khhk....',
    '....kkkk....',
    '....kwwk....',
    '....kwwk....',
    '...kwwwwk...',
    '..kwwwwwwk..',
    '.kggggggggk.',
    '.kgwggggggk.',
    '.kgwgggggGk.',
    '..kGGGGGGk..',
    '...kkkkkk...',
  ],
  trophy: [
    '..kkkkkkkk..',
    'kkkywyyyykkk',
    'k.kywyyyyk.k',
    'k.kywyyyyk.k',
    '.kkyyyyyykk.',
    '...kyyyyk...',
    '....kyyk....',
    '.....kk.....',
    '....kyyk....',
    '...kkkkkk...',
    '..koooooook.',
    '..kkkkkkkkk.',
  ],
} satisfies Record<string, string[]>
