// Pixel sprites, one string per row. '.' is transparent; every other char maps to PALETTE.
// Colors are from the Sweetie 16 palette plus a skin tone and a hair brown.
export const PALETTE: Record<string, string> = {
  k: '#0f0f1b',
  w: '#f4f4f4',
  s: '#94b0c2',
  S: '#566c86',
  y: '#ffcd75',
  o: '#ef7d57',
  r: '#b13e53',
  g: '#a7f070',
  G: '#38b764',
  T: '#257179',
  b: '#41a6f6',
  B: '#3b5dc9',
  n: '#29366f',
  c: '#73eff7',
  p: '#5d275d',
  t: '#f7c59f',
  h: '#7a4a2a',
  O: '#c05818',
  m: '#f89898',
  v: '#b088e0',
  V: '#7050a8',
  a: '#c0c0d0',
  A: '#787890',
  l: '#c8f0f8',
}

export type SpriteName = keyof typeof SPRITES

export const SPRITES = {
  hero: [
    '................',
    '.....kkkkkk.....',
    '....khhhhhhk....',
    '...khhhhhhhhk...',
    '...krrrrrrrrk...',
    '...ktkttttktk...',
    '...kttttttttk...',
    '....kttttttk....',
    '...kkBBBBBBkk...',
    '..ktkBBwwBBktk..',
    '..ktkBBBBBBktk..',
    '...kkyyyyyykk...',
    '....kBBkkBBk....',
    '....kBBkkBBk....',
    '...khhhkkhhhk...',
    '...kkkkkkkkkk...',
  ],
  house: [
    '.....kk.....',
    '....kook....',
    '...kooook...',
    '..kooooook..',
    '.kooooooook.',
    'kkkkkkkkkkkk',
    '.kyyyyyyyyk.',
    '.kybbyykkyk.',
    '.kybbyykoyk.',
    '.kyyyyykoyk.',
    '.kyyyyykoyk.',
    '.kkkkkkkkkk.',
  ],
  sword: [
    '..........kk',
    '.........kwk',
    '........kwsk',
    '.......kwsk.',
    '......kwsk..',
    '.....kwsk...',
    '.kk.kwsk....',
    '.kykwsk.....',
    '..kyyk......',
    '.kokyyk.....',
    'kokk.kyk....',
    'kk....kk....',
  ],
  meat: [
    '......kkkk..',
    '.....koooyk.',
    '....kooooyyk',
    '....koooooyk',
    '....kroooook',
    '.....krrrrk.',
    '....kwkkkk..',
    '...kwk......',
    '.kkwk.......',
    'kwwwk.......',
    'kwwk........',
    '.kk.........',
  ],
  potion: [
    '....kkkk....',
    '....khhk....',
    '....kkkk....',
    '....kwwk....',
    '....kwwk....',
    '...kwwwwk...',
    '..kwwwwwwk..',
    '.kggggggggk.',
    '.kgwggggggk.',
    '.kgwgggggGk.',
    '..kGGGGGGk..',
    '...kkkkkk...',
  ],
  trophy: [
    '..kkkkkkkk..',
    'kkkywyyyykkk',
    'k.kywyyyyk.k',
    'k.kywyyyyk.k',
    '.kkyyyyyykk.',
    '...kyyyyk...',
    '....kyyk....',
    '.....kk.....',
    '....kyyk....',
    '...kkkkkk...',
    '..koooooook.',
    '..kkkkkkkkk.',
  ],
  heart: [
    '.kk.kk.',
    'krwkrrk',
    'krrrrrk',
    '.krrrk.',
    '..krk..',
    '...k...',
  ],
  flame: [
    '...k....',
    '..kok...',
    '..kook..',
    '.kooyok.',
    'kooyyyok',
    'koyyyyok',
    'koywwyok',
    '.kkkkkk.',
  ],
  chest: [
    '.kkkkkkkkkk.',
    'khhhhhhhhhhk',
    'khyhhhhhhyhk',
    'kkkkkyykkkkk',
    'khhhkykkhhhk',
    'khyhhkkhhyhk',
    'khhhhhhhhhhk',
    'kkkkkkkkkkkk',
  ],
  skull: [
    '..kkkkk..',
    '.kwwwwwk.',
    'kwwwwwwwk',
    'kwkkwkkwk',
    'kwkkwkkwk',
    '.kwwkwwk.',
    '..kwwwk..',
    '..kkkkk..',
  ],
  tent: [
    '....kk....',
    '...kook...',
    '..kooyok..',
    '.koookyok.',
    'kooookyyok',
    'kkkkkkkkkk',
  ],
  partner: [
    '................',
    '.kk..........kk.',
    '.kok........kok.',
    '.kook......kook.',
    '.kooOkkkkkkOook.',
    '..kooooooooook..',
    '.kooooooooooook.',
    '.kookwoooowkook.',
    '.kookkooookkook.',
    '.kmoooooooooomk.',
    '.koooookkoooook.',
    '..kooyyyyyyook..',
    '..koyyyyyyyyok..',
    '...koyyyyyyok...',
    '...kook..kook...',
    '...kkkk..kkkk...',
  ],
  golem: [
    '................',
    '................',
    '....kkkkkkkk....',
    '...kaaaAAaaak...',
    '..kawaaAAaawak..',
    '..kaaaaAAaaaak..',
    '..kaAakkkkaAak..',
    '..kaaakkkkaaak..',
    'kk.kaAAAAAAak.kk',
    'kak.kAAAAAAk.kak',
    'kaakAAAAAAAAkaak',
    '.kaaAAAAAAAAaak.',
    '..kkAAAAAAAAkk..',
    '...kAAkkkkAAk...',
    '...kAAk..kAAk...',
    '...kkkk..kkkk...',
  ],
  bird: [
    '................',
    '................',
    '......kkkk......',
    '.....kbbbbk.....',
    '....kbbbbbbk....',
    'kk..kbwkkwbk..kk',
    'kbk.kbkkkkbk.kbk',
    'kbbkkbbbbbbkkbbk',
    '.kbbbbbkkbbbbbk.',
    '..kbbbkyykbbbk..',
    '...kbbllllbbk...',
    '...kbllllllbk...',
    '....kbllllbk....',
    '.....kbbbbk.....',
    '....kyk..kyk....',
    '....kk....kk....',
  ],
  blaze: [
    '................',
    '.......kk.......',
    '......kyyk......',
    '...k.kyooyk.k...',
    '..kokkooookkok..',
    '..koorrrrrrook..',
    '.korrrrrrrrrrok.',
    '.krrkwrrrrwkrrk.',
    '.krrkkrrrrkkrrk.',
    '.krrrrrrrrrrrrk.',
    '..krrrrkkrrrrk..',
    '..krryyyyyyrrk..',
    '...kryyyyyyrk...',
    '...krrk..krrk...',
    '...kkkk..kkkk...',
    '................',
  ],
  slime: [
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '....kkvvvvkk....',
    '...kvvvvvvvvk...',
    '..kvwvvvvvvwvk..',
    '..kvvvvvvvvvvk..',
    '.kvvkkkvvkkkvvk.',
    '.kvvvvvvvvvvvvk.',
    'kvvvvvvvvvvvvvvk',
    'kVvvvvvvvvvvvvVk',
    'kVVVVVVVVVVVVVVk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  badge: [
    '...kk...',
    '..kyyk..',
    '.kywyyk.',
    'kywyyyOk',
    'kyyyyyOk',
    '.kyyyOk.',
    '..kyOk..',
    '...kk...',
  ],
} satisfies Record<string, string[]>
